/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.4.1/userguide/java_library_plugin.html
 */

plugins {
    `java-library`
}

allprojects {
    repositories {
        jcenter()
    }
}

subprojects {
    apply(plugin = "java-library")
    dependencies {
        testImplementation("org.mockito:mockito-core:3.3.3")
        testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")

        testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    testImplementation("org.mockito:mockito-core:3.3.3")
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.0")

    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.6.0")
}


val test by tasks.getting(Test::class) {
    // Use junit platform for unit tests
    useJUnitPlatform()
}