name: Publish to Maven Central
on:
    workflow_dispatch
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: publish
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Maven Central Repository
                uses: actions/setup-java@v2
                with:
                    java-version: '15'
                    distribution: 'zulu'
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Create POM
                run: ./gradlew generatePomFileForMavenPublication
            -   name: Publish package
                run: ./gradlew publish --no-daemon --no-parallel
                env:
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
                    #see https://central.sonatype.org/publish/requirements/gpg/
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
                    # this helps to identify issues with GPG
                    GPG_TTY: $(tty)
