name: Publish to Maven Central
on:
    workflow_dispatch
jobs:
  publish:

    runs-on: ubuntu-latest
    environment: publish
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 15
      - name: publish  
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        with:
          gradle-version: 7.3.3
          arguments: publish --no-daemon --no-parallel --stacktrace
