name: Publish to Maven Central
on:
    workflow_dispatch
jobs:
  publish:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 15
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11
      - name: publish  
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        with:
          gradle-version: 6.6
          arguments: publish --no-daemon --no-parallel --stacktrace

      - name: closeAndReleaseRepository
        uses: gradle/gradle-build-action@v2
        with: 
           gradle-version: 6.6
           arguments: closeAndReleaseRepository --no-daemon --no-parallel
        env:
          ORG_GRADLE_PROJECT_repositoryUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_repositoryPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
