name: Publish to Maven Central
on:
    release:
        types: [ created ]
jobs:
    publish:
        runs-on: ubuntu-latest
        environment: publish
        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Maven Central Repository
                uses: actions/setup-java@v2
                with:
                    java-version: '15'
            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew
            -   name: Publish package
                run: ./gradlew publish
                env:
                    
                    ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
                    ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}
                    #see https://central.sonatype.org/publish/requirements/gpg/
                    ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_PASSPHRASE }}
                    ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
                    ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_ASCII }}
                    # this helps to identify issues with GPG
                    GPG_TTY: $(tty)
